name: Github Pages Deploy

on:
  push:
    branches:
      - "master"
  pull_request:
    branches: 
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build
        run: yarn install && yarn build
      
      - name: Deploy react app to github pages
        uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1  





