name: Github Pages Deploy

on:
  push:
    branches:
      - "master"
  pull_request:
    branches: 
      - "master"

jobs:
  install:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2

    - name: Cache node_modules
      id: cache
      uses: martijnhols/actions-cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock', 'patches') }}
        restore-keys: ${{ runner.os }}-node_modules

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install

    - name: Save "node_modules" to cache
      if: steps.cache.outputs.cache-hit != 'true'
      uses: martijnhols/actions-cache/save@v3
      with:
        path: node_modules
        key: ${{ steps.cache.outputs.primary-key }}

  build:
    needs: [install]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2

    - name: Build app
      run: yarn build

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2

    - name: Check Github User
      run: |
        git --version
        git config user.name 'doker696'
        git config user.email 'tokorev.kir@ya.ru'

    - name: Deploy react app to github pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build


